version: "3.8"

services:
  weather-radar:
    container_name: weather-radar
    build:
      context: .
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
