version: '3.8'

services:
  weather-radar:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for development
      - .:/app
      # Exclude node_modules from volume mount
      - /app/node_modules
    environment:
      - NODE_ENV=development
    # Enable container healthcheck
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
