services:
  weather-radar:
    container_name: weather-radar
    build:
      context: .
    ports:
      - "${HOST_PORT:-8080}:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    container_name: layers-backend
    build:
      context: .
      dockerfile: spring-backend/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75 -Dserver.port=8081
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8081/api/weather/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    restart: unless-stopped
